### ISSUE TITLE
Removing the highlight

### ISSUE THREAD

**Issue by perina98** [mmaciejkowalski/L.Highlight#2]
Hi, your plugin works great, however, I dont know how to remove the highlight from the map. I tried map.removeLayer, highlight.removeFrom(map) and others but none of these work. I am getting 
`Uncaught TypeError: t.onRemove is not a function`

Any idea?

**Comment by mmaciejkowalski** [comment]
Hi! Thanks for using L.Highlight!

Honestly, I forgot about onRemove() handler. I'll fix it tomorrow.

**Comment by perina98** [comment]
Thats great! Will be waiting for the update as I have team meeting on Monday. Gonna present them this great plugin!

**Comment by mmaciejkowalski** [comment]
Solved!

You can now use layer.removeFrom(map) to remove a layer. I added a demo for removing in [Github Pages](https://mmaciejkowalski.github.io/L.Highlight/#map6)
