### ISSUE TITLE
Add class to created street / polygon

### ISSUE THREAD

**Issue by perina98** [mmaciejkowalski/L.Highlight#3]
I want to animate added street or polygon (or just change color on hover of some element). 

How could this be done? I can not seem to find a way to add class to the street element.

**Comment by mmaciejkowalski** [comment]
I'll look into it into the future, for quick fix I'd suggest handling _mouseover_ and _mouseout_ events. Example for this can be shown using modified [map5](https://mmaciejkowalski.github.io/L.Highlight/#map5) from GitHub Pages:
``` 
new L.Layer.Highlight().do(
    { q: "Politechnika, Łódź", filter: "Polygon" }, 
    { style: function () { return { color: "#f00" }; }, 
    eventHandlers: { 
      click: function (area) { alert(area.sourceTarget.feature.properties.display_name); },
      mouseover: function (hoveredOver) { hoveredOver.sourceTarget.setStyle({fillColor: "#0f0", color: "#0f0"}); },
      mouseout: function (hoveredOut) { hoveredOut.sourceTarget.setStyle({fillColor: "#ccc", color: "#999"}); }
    }
  }).addTo(map5);
```

**Comment by perina98** [comment]
Thanks, I will take a look. However, what I want, is to dynamically add/remove classes or change color of polyline on hover of some other element outside the map.

**Comment by mmaciejkowalski** [comment]
It is possible, just save a refference to created layer and call `myLayer._layers[0].setStyle({...})`. Also, remember that the polygons are part of a SVG, so using CSS on them will be tricky, if not impossible.

But still, it is not the prettiest way, I will wrap it up with some fancy method in the next release.

**Comment by perina98** [comment]
You are a life saver! Thats absolutely enough! Thank you.

**Comment by perina98** [comment]
Hi, I have something like this on mouseover:

`street.setStyle({color:'red',weight:'3px',fillOpacity: .3});`

and mouseout:

`street.setStyle({color:'#2C84CB',weight:'3px',fillOpacity: .1});`

It works fine, however, after mouseout, if I zoom the map, the hovered street disappears.

Any suggestion?

EDIT:
Just to clarify - the "d" parameter of "path" of hovered street changes to "D0 0"
And my street is defined as street._layers[street._layers.length-1] a.k.a. the last added layer (I have more streets)

**Comment by perina98** [comment]
Just to clarify - the "d" parameter of "path" of hovered street changes to "D0 0"

**Comment by mmaciejkowalski** [comment]
Just debugged it, remove 'px' from _weight_ parameter and it sould work properly. It looks like there is an issue with Leaflet handling values with 'px' there.

**Comment by perina98** [comment]
You are right thanks, I feel dumb now... But also, I know its a small project (as you are the only maintainer), but maybe consider adding some error outputs when something goes wrong... I didnt know how to debug that.

**Comment by mmaciejkowalski** [comment]
But there was no error there from leaflet, it was just a hunch I checked. There's no other way to solve this kind of issues than trial and error 😄

**Comment by perina98** [comment]
Hi,

just wanted to let you know that this way of adding streets

`new L.Layer.Highlight().do({
                    street: 'Piotrkowska', city: 'Łódź'
                }).addTo(searchMap);`

is not working for me... It works using q parameter, but I need more accuracy, as using the q parameter also draws streets "outside" the city I want (for example Praha, 5. května draws like 10 streets) 

`new L.Layer.Highlight().do({
                    q:"5. května, Praha"
                }).addTo(searchMap);`

**Comment by perina98** [comment]
Hi, I am still curious about if that was fixed or you take a look at it in the future? Thanks for feedback.

**Comment by mmaciejkowalski** [comment]
Hi, I know more than a year passed and I don't know if it's still relevant, but using english names often fix things, because it will not catch stuff like regions etc. So, `"5. května, Prague"` is a solution for your troubles

**Comment by perina98** [comment]
The project got postponed, but I am glad that if it resumes, I have the
answer ready. thx



S pozdravom / best regards,
Lukáš Perina.
